driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
  - name: centos-6.6
    driver:
        box: chef/centos-6.6
        box_url: chef/centos-6.6
        network:
        - ["private_network", { ip: "192.168.34.56" }]

suites:
  - name: nginx
    run_list:
      - recipe[wordpress::nginx]
    attributes:
      mysql:
        server_root_password: "Please-Dont-Use-In-Production"
        server_debian_password: "Please-Dont-Use-In-Production"
        server_repl_password: "Please-Dont-Use-In-Production"
